/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
If you want to view the source, please visit the GitHub repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MergeTablePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var MAX_DEPTH = 8;
var DEPTH_ATTR = "data-merge-depth";
var MergeTablePlugin = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    /** MutationObservers attached to Live Preview editor panes, keyed by leaf id. */
    this.leafObservers = /* @__PURE__ */ new Map();
  }
  async onload() {
    console.log("Merge Table Plugin: loading");
    this.registerMarkdownCodeBlockProcessor(
      "merge-table",
      async (source, el, ctx) => {
        const depth = this.getDepthFromDOM(el);
        await this.handleCodeBlock(source, el, ctx, depth);
      }
    );
    this.registerMarkdownPostProcessor(async (el, ctx) => {
      await this.resolveMergeTableEmbeds(el, ctx.sourcePath);
    });
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (leaf) => {
        if (leaf)
          this.attachLeafObserver(leaf);
      })
    );
    this.registerEvent(
      this.app.workspace.on("layout-change", () => {
        this.app.workspace.iterateAllLeaves((leaf) => {
          this.attachLeafObserver(leaf);
        });
      })
    );
    this.app.workspace.iterateAllLeaves((leaf) => {
      this.attachLeafObserver(leaf);
    });
  }
  onunload() {
    this.leafObservers.forEach((obs) => obs.disconnect());
    this.leafObservers.clear();
    console.log("Merge Table Plugin: unloading");
  }
  // ── MutationObserver management ───────────────────────────────────────────
  /**
   * Attach a MutationObserver to `leaf`'s container.
   *
   * Key design decisions:
   *  - Source path is read dynamically at callback time (not captured once at
   *    attach time) so file switches within the same pane are handled correctly.
   *  - We watch for attribute mutations too (subtree:true, attributes:true) so
   *    we catch the moment Obsidian stamps `is-unresolved` onto an embed it
   *    couldn't resolve — that's our reliable trigger.
   *  - We use setTimeout(0) inside the callback so Obsidian fully finishes its
   *    own (failed) async resolution before we replace the content; without
   *    this Obsidian can overwrite what we render.
   */
  attachLeafObserver(leaf) {
    var _a;
    const leafId = leaf.id;
    if (!leafId || this.leafObservers.has(leafId))
      return;
    const container = (_a = leaf.view) == null ? void 0 : _a.containerEl;
    if (!container)
      return;
    const observer = new MutationObserver(() => {
      const sourcePath2 = this.getLeafSourcePath(leaf);
      if (!sourcePath2)
        return;
      setTimeout(() => this.resolveEmbedsInEl(container, sourcePath2), 0);
    });
    observer.observe(container, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["class", "src", "data-href"]
    });
    this.leafObservers.set(leafId, observer);
    const sourcePath = this.getLeafSourcePath(leaf);
    if (sourcePath) {
      setTimeout(() => this.resolveEmbedsInEl(container, sourcePath), 0);
    }
  }
  /** Return the file path of the note open in `leaf`, or null. */
  getLeafSourcePath(leaf) {
    var _a, _b;
    const view = leaf.view;
    return (_b = (_a = view == null ? void 0 : view.file) == null ? void 0 : _a.path) != null ? _b : null;
  }
  // ══════════════════════════════════════════════════════════════════════════
  // EMBED RESOLUTION
  // ══════════════════════════════════════════════════════════════════════════
  // ── Reading mode entry point ─────────────────────────────────────────────
  async resolveMergeTableEmbeds(el, sourcePath) {
    const embeds = Array.from(
      el.querySelectorAll(".internal-embed")
    );
    for (const embed of embeds) {
      await this.resolveOneEmbed(embed, sourcePath);
    }
  }
  // ── Live Preview entry point (called by MutationObserver) ─────────────────
  /**
   * Scan `el` and its subtree for internal-embed elements that:
   *   (a) reference a block ID (src contains "#^"), AND
   *   (b) are unresolved — Obsidian stamps `is-unresolved` when MetadataCache
   *       lookup fails, which is always the case for merge-table content.
   *
   * We also catch embeds without `is-unresolved` in case the class timing
   * differs between Obsidian versions.
   *
   * `data-merge-resolved` guards against double-processing across observer
   * callbacks.
   */
  resolveEmbedsInEl(el, sourcePath) {
    var _a, _b;
    const selectors = [
      ".internal-embed.is-unresolved",
      ".internal-embed[src*='#^']",
      ".internal-embed[data-href*='#^']"
    ];
    const seen = /* @__PURE__ */ new Set();
    const embeds = [];
    for (const sel of selectors) {
      el.querySelectorAll(sel).forEach((node) => {
        if (!seen.has(node)) {
          seen.add(node);
          embeds.push(node);
        }
      });
      if (el.matches(sel) && !seen.has(el)) {
        seen.add(el);
        embeds.push(el);
      }
    }
    for (const embed of embeds) {
      const src = (_b = (_a = embed.getAttribute("src")) != null ? _a : embed.getAttribute("data-href")) != null ? _b : "";
      if (!src.includes("#^"))
        continue;
      if (embed.getAttribute("data-merge-resolved") === "done")
        continue;
      embed.setAttribute("data-merge-resolved", "pending");
      this.resolveOneEmbed(embed, sourcePath).then(() => embed.setAttribute("data-merge-resolved", "done")).catch(() => embed.removeAttribute("data-merge-resolved"));
    }
  }
  // ── Shared per-embed resolver ─────────────────────────────────────────────
  /**
   * Resolve a single internal-embed element.
   * Reads the referenced file, finds the block in any merge-table block,
   * and re-renders the embed content if a match is found.
   */
  async resolveOneEmbed(embed, sourcePath) {
    var _a, _b, _c;
    const src = (_c = (_b = (_a = embed.getAttribute("src")) != null ? _a : embed.getAttribute("data-href")) != null ? _b : embed.getAttribute("alt")) != null ? _c : "";
    if (!src.includes("#^"))
      return;
    const caretIdx = src.indexOf("#^");
    const filePart = src.slice(0, caretIdx);
    const blockId = src.slice(caretIdx + 2);
    if (!blockId)
      return;
    const targetFile = this.app.metadataCache.getFirstLinkpathDest(
      filePart,
      sourcePath
    );
    if (!targetFile)
      return;
    let fileContent;
    try {
      fileContent = await this.app.vault.cachedRead(targetFile);
    } catch (e) {
      return;
    }
    const blockMarkdown = this.extractBlockFromMergeTables(fileContent, blockId);
    if (blockMarkdown == null)
      return;
    embed.empty();
    embed.removeAttribute("class");
    embed.addClass("internal-embed", "merge-table-embed");
    const inner = embed.createDiv({ cls: "markdown-embed" });
    const content = inner.createDiv({ cls: "markdown-embed-content" });
    const page = content.createDiv({ cls: "markdown-preview-view" });
    await this.renderMarkdownSimple(blockMarkdown, page, targetFile.path);
  }
  // ─── Extract a ^blockid from the merge-table blocks in a raw file ──────────
  /**
   * Parse all merge-table code blocks in `fileContent` and return the markdown
   * content of the block annotated with `^blockId`.
   *
   * Returns null if no matching block is found.
   */
  extractBlockFromMergeTables(fileContent, blockId) {
    const fenceRe = /^```merge-table\r?\n([\s\S]*?)^```/gm;
    let fenceMatch;
    while ((fenceMatch = fenceRe.exec(fileContent)) !== null) {
      const json = fenceMatch[1];
      let tableDef;
      try {
        tableDef = JSON.parse(json);
      } catch (e) {
        continue;
      }
      if (!Array.isArray(tableDef.rows))
        continue;
      const result = this.findBlockIdInTableDef(tableDef, blockId);
      if (result != null)
        return result;
    }
    return null;
  }
  /**
   * Recursively walk a TableDef looking for a string block that contains
   * `^blockId`.  Returns the markdown of the specific annotated block
   * (stripping the ^id marker itself), or null if not found.
   */
  findBlockIdInTableDef(tableDef, blockId) {
    for (const row of tableDef.rows) {
      for (const cell of row) {
        if (cell === null)
          continue;
        if (typeof cell === "string") {
          const extracted = this.extractAnnotatedBlock(cell, blockId);
          if (extracted != null)
            return extracted;
          continue;
        }
        if (cell.content != null) {
          const blocks = this.normaliseContent(cell.content);
          for (const block of blocks) {
            if (typeof block === "string") {
              const extracted = this.extractAnnotatedBlock(block, blockId);
              if (extracted != null)
                return extracted;
            } else {
              const nested = this.findBlockIdInTableDef(block, blockId);
              if (nested != null)
                return nested;
            }
          }
        }
      }
    }
    return null;
  }
  /**
   * Given a markdown string `content`, extract the specific block annotated
   * with `^blockId`.
   *
   * Obsidian associates a `^id` with the block immediately preceding it.
   * We approximate that by finding the segment between the previous blank line
   * (or string start) and the line containing `^id`.
   *
   * Returns the block text without the `^id` marker, or null if not found.
   */
  extractAnnotatedBlock(content, blockId) {
    const idPattern = new RegExp(`(?:^|\\n)\\^${blockId}(?:\\s|$)`);
    const idMatch = idPattern.exec(content);
    if (!idMatch)
      return null;
    const idLineStart = idMatch.index === 0 ? 0 : idMatch.index + 1;
    const idLineEnd = content.indexOf("\n", idLineStart);
    const afterId = idLineEnd >= 0 ? idLineEnd + 1 : content.length;
    const beforeId = content.slice(0, idLineStart);
    const lastBlank = beforeId.lastIndexOf("\n\n");
    const blockStart = lastBlank >= 0 ? lastBlank + 2 : 0;
    const blockText = content.slice(blockStart, idLineStart).trimEnd();
    return blockText.length > 0 ? blockText : null;
  }
  // ══════════════════════════════════════════════════════════════════════════
  // TABLE RENDERING
  // ══════════════════════════════════════════════════════════════════════════
  getDepthFromDOM(el) {
    var _a;
    let node = el.parentElement;
    while (node) {
      if (node.classList.contains("merge-table-wrapper")) {
        return parseInt((_a = node.getAttribute(DEPTH_ATTR)) != null ? _a : "0", 10) + 1;
      }
      node = node.parentElement;
    }
    return 0;
  }
  async handleCodeBlock(source, el, ctx, depth) {
    if (depth > MAX_DEPTH) {
      this.renderError(
        el,
        "Max nesting depth exceeded",
        `Tables can be nested up to ${MAX_DEPTH} levels deep.`,
        source
      );
      return;
    }
    let tableDef;
    try {
      tableDef = JSON.parse(source.trim());
    } catch (err) {
      this.renderError(el, "Invalid JSON", String(err), source);
      return;
    }
    if (!Array.isArray(tableDef.rows)) {
      this.renderError(
        el,
        "Missing `rows` array",
        'The table definition must have a "rows" key.',
        source
      );
      return;
    }
    try {
      await this.renderTable(tableDef, el, ctx, depth);
    } catch (err) {
      this.renderError(el, "Render error", String(err), source);
    }
  }
  async renderTable(tableDef, el, ctx, depth) {
    var _a, _b;
    const wrapper = el.createDiv({ cls: "merge-table-wrapper" });
    wrapper.setAttribute(DEPTH_ATTR, String(depth));
    wrapper.addClass(`merge-table-depth-${depth}`);
    const table = wrapper.createEl("table", { cls: "merge-table" });
    if (tableDef.tableStyle)
      table.setAttribute("style", tableDef.tableStyle);
    if (tableDef.caption) {
      const captionEl = table.createEl("caption", { cls: "merge-table-caption" });
      await this.renderMarkdown(tableDef.caption, captionEl, ctx, wrapper);
    }
    const tbody = table.createEl("tbody");
    const occupiedGrid = /* @__PURE__ */ new Map();
    const key = (r, c) => `${r},${c}`;
    const isOccupied = (r, c) => occupiedGrid.get(key(r, c)) === true;
    const markOccupied = (r, c) => occupiedGrid.set(key(r, c), true);
    for (let rowIdx = 0; rowIdx < tableDef.rows.length; rowIdx++) {
      const tr = tbody.createEl("tr");
      const rowDef = tableDef.rows[rowIdx];
      let defIdx = 0, gridCol = 0;
      while (defIdx < rowDef.length) {
        while (isOccupied(rowIdx, gridCol))
          gridCol++;
        const cellValue = rowDef[defIdx++];
        if (cellValue === null) {
          gridCol++;
          continue;
        }
        const cell = typeof cellValue === "string" ? { content: cellValue } : cellValue;
        const colspan = Math.max(1, (_a = cell.colspan) != null ? _a : 1);
        const rowspan = Math.max(1, (_b = cell.rowspan) != null ? _b : 1);
        const tag = cell.header ? "th" : "td";
        const td = tr.createEl(tag, { cls: "merge-table-cell" });
        if (colspan > 1)
          td.colSpan = colspan;
        if (rowspan > 1)
          td.rowSpan = rowspan;
        for (let dr = 0; dr < rowspan; dr++)
          for (let dc = 0; dc < colspan; dc++)
            if (dr !== 0 || dc !== 0)
              markOccupied(rowIdx + dr, gridCol + dc);
        const styles = [];
        if (cell.bg) {
          const c = this.validateColor(cell.bg);
          if (c)
            styles.push(`background-color: ${c}`);
        }
        if (cell.color) {
          const c = this.validateColor(cell.color);
          if (c)
            styles.push(`color: ${c}`);
        }
        if (cell.align)
          styles.push(`text-align: ${cell.align}`);
        if (cell.valign)
          styles.push(`vertical-align: ${cell.valign}`);
        if (styles.length)
          td.setAttribute("style", styles.join("; "));
        if (cell.content != null) {
          for (const block of this.normaliseContent(cell.content)) {
            await this.renderBlock(block, td, ctx, depth, wrapper);
          }
        }
        gridCol += colspan;
      }
    }
  }
  normaliseContent(value) {
    if (typeof value === "string")
      return [value];
    if (Array.isArray(value))
      return value;
    return [value];
  }
  async renderBlock(block, parent, ctx, depth, anchorRoot) {
    if (typeof block === "string") {
      if (!block.length)
        return;
      const div = parent.createDiv({ cls: "merge-table-cell-content" });
      await this.renderMarkdown(block, div, ctx, anchorRoot);
    } else {
      if (depth >= MAX_DEPTH) {
        this.renderError(
          parent,
          "Max nesting depth exceeded",
          `Tables can be nested up to ${MAX_DEPTH} levels deep.`,
          ""
        );
        return;
      }
      if (!Array.isArray(block.rows)) {
        this.renderError(
          parent,
          "Invalid nested table",
          'Each table block must have a "rows" array.',
          ""
        );
        return;
      }
      await this.renderTable(
        block,
        parent.createDiv({ cls: "merge-table-cell-content" }),
        ctx,
        depth + 1
      );
    }
  }
  // ── Markdown rendering + anchor hoisting ────────────────────────────────
  async renderMarkdown(markdown, el, ctx, anchorRoot) {
    if (typeof import_obsidian.MarkdownRenderer["render"] === "function") {
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, el, ctx.sourcePath, this);
    } else {
      await import_obsidian.MarkdownRenderer.renderMarkdown(
        markdown,
        el,
        ctx.sourcePath,
        this
      );
    }
    el.querySelectorAll("[id]").forEach((node) => {
      const id = node.getAttribute("id");
      if (id)
        this.hoistBlockAnchor(id, node, anchorRoot);
    });
  }
  /** Render markdown without a MarkdownPostProcessorContext (used for embeds). */
  async renderMarkdownSimple(markdown, el, sourcePath) {
    if (typeof import_obsidian.MarkdownRenderer["render"] === "function") {
      await import_obsidian.MarkdownRenderer.render(this.app, markdown, el, sourcePath, this);
    } else {
      await import_obsidian.MarkdownRenderer.renderMarkdown(
        markdown,
        el,
        sourcePath,
        this
      );
    }
  }
  hoistBlockAnchor(blockId, sourceEl, anchorRoot) {
    const escapedId = CSS.escape(blockId);
    if (anchorRoot.querySelector(`span.merge-table-anchor[id="${escapedId}"]`))
      return;
    const anchor = anchorRoot.createEl("span", { cls: "merge-table-anchor" });
    anchor.id = blockId;
    const ghost = anchorRoot.createDiv({ cls: "merge-table-anchor-ghost" });
    ghost.innerHTML = sourceEl.outerHTML;
  }
  // ── Colour validation ────────────────────────────────────────────────────
  validateColor(raw) {
    const s = raw.trim();
    if (/^#([0-9a-fA-F]{3,8})$/.test(s))
      return s;
    if (/^(rgb|rgba|hsl|hsla)\s*\([^)]*\)$/i.test(s))
      return s;
    if (/^[a-zA-Z]{2,30}$/.test(s))
      return s;
    return null;
  }
  // ── Error display ────────────────────────────────────────────────────────
  renderError(el, title, message, source) {
    const div = el.createDiv({ cls: "merge-table-error" });
    div.createEl("strong", { text: `\u26A0 Merge Table \u2013 ${title}: ` });
    div.createSpan({ text: message });
    if (source) {
      const pre = div.createEl("pre", { cls: "merge-table-error-source" });
      pre.createEl("code", { text: source });
    }
  }
};
